from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor


MONTHS_PER_YEAR = 12
DEFAULT_COST_RATE = 0.001
TICKERS = ["SPY", "QQQ", "TLT", "GLD", "VNQ", "DBC"]

MODEL_GROUPS = {
    "ai_high_risk": "ai_risk_profile",
    "ai_low_risk": "ai_risk_profile",
    "ai_medium_risk": "ai_risk_profile",
    "pto_markowitz": "predict_then_optimize",
    "spo_plus": "spo_model",
    "spo_plus_fee": "spo_model",
    "spo_plus_turnover_l2": "spo_model",
}

BENCHMARKS = {
    "equal_weight_6etf": "benchmark",
    "spy_buy_hold": "benchmark",
}

STRATEGY_NOTES = {
    "ai_high_risk": "AI high-risk profile, constrained optimizer using SPO/PtO and risk inputs.",
    "ai_low_risk": "AI low-risk profile, constrained optimizer using SPO/PtO and risk inputs.",
    "ai_medium_risk": "AI medium-risk profile, constrained optimizer using SPO/PtO and risk inputs.",
    "equal_weight_6etf": "Static equal-weight 6 ETF benchmark.",
    "pto_markowitz": "Ridge predict-then-optimize with Markowitz max-Sharpe allocation.",
    "spo_plus": "PyEPO SPO+ decision-focused linear model with max-return allocation.",
    "spo_plus_fee": "SPO+ allocation with transaction-fee term.",
    "spo_plus_turnover_l2": "SPO+ allocation with turnover and L2 weight regularization.",
    "spy_buy_hold": "SPY buy-and-hold benchmark.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Backtest and evaluate existing ETF strategy/model outputs generated by "
            "src/reproduce_spo_paper.py and src/generate_ai_risk_profiles.py."
        )
    )
    parser.add_argument(
        "--input-dir",
        default="outputs/tables",
        help="Directory containing existing model output tables.",
    )
    parser.add_argument(
        "--output-dir",
        default="test/backtest_outputs",
        help="Directory for independent backtest evaluation artifacts.",
    )
    parser.add_argument(
        "--benchmark",
        default="equal_weight_6etf",
        choices=sorted(BENCHMARKS),
        help="Primary benchmark for excess-return and alpha diagnostics.",
    )
    parser.add_argument(
        "--cost-rate",
        type=float,
        default=DEFAULT_COST_RATE,
        help=(
            "One-way transaction cost rate. Main net results are recomputed from "
            "gross_return - turnover * cost_rate."
        ),
    )
    return parser.parse_args()


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required input file is missing: {path}")


def read_existing_returns(input_dir: Path) -> pd.DataFrame:
    spo_path = input_dir / "spo_backtest_returns.csv"
    ai_path = input_dir / "ai_risk_profile_backtest_returns.csv"
    require_file(spo_path)
    require_file(ai_path)

    frames = [
        pd.read_csv(spo_path, parse_dates=["date"]),
        pd.read_csv(ai_path, parse_dates=["date"]),
    ]
    returns = pd.concat(frames, ignore_index=True)
    returns = returns.drop_duplicates(["date", "strategy"], keep="last")
    expected_cols = {
        "date",
        "strategy",
        "gross_return",
        "turnover",
        "transaction_cost_rate",
        "transaction_cost",
        "net_return",
    }
    missing = expected_cols.difference(returns.columns)
    if missing:
        raise ValueError(f"Backtest return table is missing columns: {sorted(missing)}")
    return returns.sort_values(["strategy", "date"]).reset_index(drop=True)


def apply_transaction_cost(backtest_returns: pd.DataFrame, cost_rate: float) -> pd.DataFrame:
    out = backtest_returns.copy()
    out["source_net_return"] = out["net_return"]
    out["source_transaction_cost_rate"] = out["transaction_cost_rate"]
    out["transaction_cost_rate"] = float(cost_rate)
    out["transaction_cost"] = out["turnover"].astype(float) * float(cost_rate)
    out["net_return"] = out["gross_return"].astype(float) - out["transaction_cost"]
    return out


def read_price_index(root: Path) -> pd.DataFrame:
    path = root / "data" / "processed" / "prices_adj_close.csv"
    require_file(path)
    prices = pd.read_csv(path, parse_dates=["Date"]).rename(columns={"Date": "date"})
    prices = prices.set_index("date").reindex(columns=TICKERS).dropna(how="all")
    return prices / prices.iloc[0]


def read_strategy_weights(input_dir: Path) -> pd.DataFrame:
    spo_path = input_dir / "spo_portfolio_weights.csv"
    ai_path = input_dir / "ai_risk_profile_weights.csv"
    require_file(spo_path)
    require_file(ai_path)
    weights = pd.concat(
        [
            pd.read_csv(spo_path, parse_dates=["date"]),
            pd.read_csv(ai_path, parse_dates=["date"]),
        ],
        ignore_index=True,
        sort=False,
    )
    expected_cols = {"date", "strategy", "ticker", "weight"}
    missing = expected_cols.difference(weights.columns)
    if missing:
        raise ValueError(f"Weight table is missing columns: {sorted(missing)}")
    return weights.sort_values(["strategy", "date", "ticker"]).reset_index(drop=True)


def read_feature_metadata(root: Path) -> dict[str, Any]:
    path = root / "outputs" / "tables" / "feature_dataset_quality.json"
    require_file(path)
    return json.loads(path.read_text(encoding="utf-8"))


def build_lookahead_audit(
    root: Path,
    input_dir: Path,
    backtest_returns: pd.DataFrame,
    feature_metadata: dict[str, Any],
    validation_summary: dict[str, Any],
) -> dict[str, Any]:
    modeling_path = root / "data" / "processed" / "modeling_dataset_monthly_rebalance.csv"
    require_file(modeling_path)
    monthly = pd.read_csv(modeling_path, parse_dates=["date"])
    scores_path = input_dir / "spo_prediction_scores.csv"
    require_file(scores_path)
    scores = pd.read_csv(scores_path, parse_dates=["date"])
    test_rows = monthly[monthly["split"] == "test"]
    train_valid_rows = monthly[monthly["split"].isin(["train", "valid"])]

    source = (root / "src" / "reproduce_spo_paper.py").read_text(encoding="utf-8")
    feature_config = feature_metadata.get("feature_config", {})
    quality_summary = feature_metadata.get("quality_summary", {})
    spo_data = validation_summary.get("spo_metadata", {}).get("data", {})

    backtest_dates = pd.Series(backtest_returns["date"].drop_duplicates()).sort_values()
    test_dates = pd.Series(scores["date"].drop_duplicates()).sort_values()
    same_test_start = (
        bool(backtest_dates.iloc[0] == test_dates.iloc[0])
        if len(backtest_dates) and len(test_dates)
        else False
    )
    same_test_end = (
        bool(backtest_dates.iloc[-1] == test_dates.iloc[-1])
        if len(backtest_dates) and len(test_dates)
        else False
    )

    checks = [
        {
            "rule": "t month-end features only use data observed at or before sample date",
            "status": feature_config.get("feature_lag_rule", "").lower().startswith("all features use"),
            "evidence": feature_config.get("feature_lag_rule", ""),
        },
        {
            "rule": "t month-end features predict t+1 month / forward 21-trading-day returns",
            "status": "Forward 21" in feature_config.get("label_rule", ""),
            "evidence": feature_config.get("label_rule", ""),
        },
        {
            "rule": "portfolio return uses the next-period realized return already stored as future_return_21d",
            "status": same_test_start and same_test_end,
            "evidence": (
                f"backtest_dates={backtest_dates.iloc[0].date()}..{backtest_dates.iloc[-1].date()}, "
                f"test_label_dates={test_dates.iloc[0].date()}..{test_dates.iloc[-1].date()}"
                if len(backtest_dates) and len(test_dates)
                else "missing dates"
            ),
        },
        {
            "rule": "StandardScaler is fit on train split only, then transforms validation and test",
            "status": (
                "train_panel = monthly_panel[monthly_panel[\"split\"] == \"train\"]" in source
                and "fit_scaler=True" in source
                and "fit_scaler=False" in source
                and validation_summary.get("spo_metadata", {})
                .get("data", {})
                .get("scaler_fit_rule", "")
                .startswith("StandardScaler is fit on train split only")
            ),
            "evidence": (
                validation_summary.get("spo_metadata", {})
                .get("data", {})
                .get("scaler_fit_rule", "missing scaler metadata")
            ),
        },
        {
            "rule": "split dates keep test data after training/validation period",
            "status": (
                not train_valid_rows.empty
                and not test_rows.empty
                and train_valid_rows["date"].max() < test_rows["date"].min()
            ),
            "evidence": (
                f"train_valid_end={train_valid_rows['date'].max().date()}, "
                f"test_start={test_rows['date'].min().date()}"
            ),
        },
    ]
    all_passed = bool(all(item["status"] for item in checks))
    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "all_checks_passed": all_passed,
        "input_dir": str(input_dir),
        "feature_count": quality_summary.get("feature_count", len(quality_summary.get("feature_names", []))),
        "split_rule": feature_config.get("split_rule", ""),
        "model_fit_rule": spo_data.get("model_fit_rule"),
        "metadata_test_start": spo_data.get("test_start"),
        "metadata_test_end": spo_data.get("test_end"),
        "checks": checks,
    }


def build_random_forest_feature_importance(
    root: Path,
    feature_metadata: dict[str, Any],
    output_dir: Path,
) -> pd.DataFrame:
    modeling_path = root / "data" / "processed" / "modeling_dataset.csv"
    require_file(modeling_path)
    modeling = pd.read_csv(modeling_path, parse_dates=["date"])
    feature_names = feature_metadata["quality_summary"]["feature_names"]
    train = modeling[modeling["split"] == "train"].dropna(
        subset=feature_names + ["future_return_21d"]
    )
    if train.empty:
        raise ValueError("Training data is empty; cannot build RF feature importance.")

    model = RandomForestRegressor(
        n_estimators=300,
        max_depth=6,
        min_samples_leaf=10,
        random_state=42,
        n_jobs=-1,
    )
    model.fit(train[feature_names], train["future_return_21d"])
    importance = (
        pd.DataFrame(
            {
                "feature": feature_names,
                "importance": model.feature_importances_,
            }
        )
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )
    importance["rank"] = importance.index + 1
    importance.to_csv(output_dir / "random_forest_feature_importance.csv", index=False)
    return importance


def ensure_plot_dir(output_dir: Path) -> Path:
    plot_dir = output_dir / "plots"
    plot_dir.mkdir(parents=True, exist_ok=True)
    return plot_dir


def save_etf_price_chart(price_index: pd.DataFrame, output_dir: Path) -> str:
    plot_dir = ensure_plot_dir(output_dir)
    path = plot_dir / "etf_price_index.png"
    fig, ax = plt.subplots(figsize=(12, 6))
    price_index.plot(ax=ax, linewidth=1.4)
    ax.set_title("ETF Price Index (start = 1.0)")
    ax.set_xlabel("Date")
    ax.set_ylabel("Indexed adjusted close")
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=3, fontsize=9)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return str(path)


def save_strategy_equity_chart(curves: pd.DataFrame, output_dir: Path) -> str:
    plot_dir = ensure_plot_dir(output_dir)
    path = plot_dir / "strategy_cumulative_returns.png"
    pivot = curves.pivot(index="date", columns="strategy", values="net_wealth").sort_index()
    fig, ax = plt.subplots(figsize=(12, 6))
    pivot.plot(ax=ax, linewidth=1.5)
    ax.set_title("Strategy Cumulative Net Wealth")
    ax.set_xlabel("Date")
    ax.set_ylabel("Net wealth")
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=3, fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return str(path)


def save_strategy_drawdown_chart(curves: pd.DataFrame, output_dir: Path) -> str:
    plot_dir = ensure_plot_dir(output_dir)
    path = plot_dir / "strategy_drawdowns.png"
    pivot = curves.pivot(index="date", columns="strategy", values="net_drawdown").sort_index()
    fig, ax = plt.subplots(figsize=(12, 6))
    pivot.plot(ax=ax, linewidth=1.4)
    ax.set_title("Strategy Net Drawdowns")
    ax.set_xlabel("Date")
    ax.set_ylabel("Drawdown")
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=3, fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return str(path)


def save_ai_weight_heatmap(weights: pd.DataFrame, output_dir: Path) -> str:
    plot_dir = ensure_plot_dir(output_dir)
    path = plot_dir / "ai_monthly_weight_heatmap.png"
    ai = weights[weights["strategy"].str.startswith("ai_")].copy()
    if ai.empty:
        raise ValueError("No AI strategy weights found for heatmap.")
    ai["date"] = pd.to_datetime(ai["date"]).dt.strftime("%Y-%m")
    matrix = ai.pivot_table(
        index=["strategy", "date"],
        columns="ticker",
        values="weight",
        aggfunc="sum",
    ).reindex(columns=TICKERS)
    fig_height = max(6, 0.18 * len(matrix))
    fig, ax = plt.subplots(figsize=(9, fig_height))
    image = ax.imshow(matrix.to_numpy(dtype=float), aspect="auto", cmap="YlGnBu", vmin=0, vmax=1)
    ax.set_title("AI Monthly Portfolio Weights")
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_xticklabels(matrix.columns)
    ax.set_yticks(range(len(matrix.index)))
    ax.set_yticklabels([f"{s} {d}" for s, d in matrix.index], fontsize=6)
    fig.colorbar(image, ax=ax, label="Weight")
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return str(path)


def save_rf_importance_chart(importance: pd.DataFrame, output_dir: Path) -> str:
    plot_dir = ensure_plot_dir(output_dir)
    path = plot_dir / "random_forest_feature_importance.png"
    top = importance.sort_values("importance", ascending=True).tail(15)
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.barh(top["feature"], top["importance"], color="#4c78a8")
    ax.set_title("Random Forest Feature Importance (fit on train split only)")
    ax.set_xlabel("Importance")
    ax.grid(axis="x", alpha=0.25)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return str(path)


def save_performance_table_chart(metrics: pd.DataFrame, output_dir: Path) -> str:
    plot_dir = ensure_plot_dir(output_dir)
    path = plot_dir / "strategy_performance_table.png"
    net = metrics[metrics["return_type"] == "net"].sort_values("annual_return", ascending=False)
    display = net[
        [
            "strategy",
            "annual_return",
            "annual_volatility",
            "sharpe",
            "max_drawdown",
            "win_rate",
            "average_turnover",
            "calmar",
        ]
    ].copy()
    for col in [
        "annual_return",
        "annual_volatility",
        "max_drawdown",
        "win_rate",
        "average_turnover",
    ]:
        display[col] = display[col].map(lambda x: f"{x * 100:.2f}%")
    display["sharpe"] = display["sharpe"].map(lambda x: f"{x:.2f}")
    display["calmar"] = display["calmar"].map(lambda x: f"{x:.2f}")

    fig, ax = plt.subplots(figsize=(13, 0.55 * len(display) + 1.5))
    ax.axis("off")
    table = ax.table(
        cellText=display.to_numpy(),
        colLabels=display.columns,
        cellLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.25)
    ax.set_title("Strategy Performance Comparison (Net)", pad=12)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)
    return str(path)


def save_all_plots(
    price_index: pd.DataFrame,
    curves: pd.DataFrame,
    weights: pd.DataFrame,
    metrics: pd.DataFrame,
    importance: pd.DataFrame,
    output_dir: Path,
) -> dict[str, str]:
    return {
        "etf_price_index": save_etf_price_chart(price_index, output_dir),
        "strategy_cumulative_returns": save_strategy_equity_chart(curves, output_dir),
        "strategy_drawdowns": save_strategy_drawdown_chart(curves, output_dir),
        "ai_monthly_weight_heatmap": save_ai_weight_heatmap(weights, output_dir),
        "random_forest_feature_importance": save_rf_importance_chart(importance, output_dir),
        "strategy_performance_table": save_performance_table_chart(metrics, output_dir),
    }


def read_prediction_metrics(input_dir: Path) -> pd.DataFrame:
    path = input_dir / "spo_model_metrics.csv"
    require_file(path)
    return pd.read_csv(path)


def read_validation_summary(input_dir: Path) -> dict[str, Any]:
    validation_path = input_dir / "ai_risk_profile_validation.json"
    metadata_path = input_dir / "spo_reproduction_metadata.json"
    summary: dict[str, Any] = {}
    if validation_path.exists():
        summary["ai_validation"] = json.loads(validation_path.read_text(encoding="utf-8"))
    if metadata_path.exists():
        summary["spo_metadata"] = json.loads(metadata_path.read_text(encoding="utf-8"))
    return summary


def max_drawdown(return_series: pd.Series) -> float:
    wealth = (1.0 + return_series.fillna(0.0)).cumprod()
    if wealth.empty:
        return 0.0
    return float((wealth / wealth.cummax() - 1.0).min())


def drawdown_series_from_wealth(wealth: pd.Series) -> pd.Series:
    if wealth.empty:
        return wealth
    return wealth / wealth.cummax() - 1.0


def longest_drawdown_months(return_series: pd.Series) -> int:
    wealth = (1.0 + return_series.fillna(0.0)).cumprod()
    if wealth.empty:
        return 0
    peak = wealth.cummax()
    below_peak = wealth < peak
    longest = 0
    current = 0
    for flag in below_peak:
        current = current + 1 if flag else 0
        longest = max(longest, current)
    return int(longest)


def evaluate_returns(returns: pd.Series, turnover: pd.Series) -> dict[str, Any]:
    clean_returns = returns.fillna(0.0).astype(float)
    n = len(clean_returns)
    wealth = float((1.0 + clean_returns).prod()) if n else 1.0
    annual_return = wealth ** (MONTHS_PER_YEAR / n) - 1.0 if n else 0.0
    annual_vol = (
        float(clean_returns.std(ddof=1) * np.sqrt(MONTHS_PER_YEAR)) if n > 1 else 0.0
    )
    downside = clean_returns[clean_returns < 0]
    downside_vol = (
        float(downside.std(ddof=1) * np.sqrt(MONTHS_PER_YEAR)) if len(downside) > 1 else 0.0
    )
    best_month = float(clean_returns.max()) if n else 0.0
    worst_month = float(clean_returns.min()) if n else 0.0
    mdd = max_drawdown(clean_returns)
    return {
        "months": int(n),
        "total_return": wealth - 1.0,
        "annual_return": annual_return,
        "annual_volatility": annual_vol,
        "sharpe": annual_return / annual_vol if annual_vol > 0 else 0.0,
        "sortino": annual_return / downside_vol if downside_vol > 0 else 0.0,
        "max_drawdown": mdd,
        "calmar": annual_return / abs(mdd) if mdd < 0 else 0.0,
        "longest_drawdown_months": longest_drawdown_months(clean_returns),
        "win_rate": float((clean_returns > 0).mean()) if n else 0.0,
        "best_month": best_month,
        "worst_month": worst_month,
        "average_monthly_return": float(clean_returns.mean()) if n else 0.0,
        "average_turnover": float(turnover.mean()) if len(turnover) else 0.0,
        "final_wealth": wealth,
    }


def calculate_metrics(backtest_returns: pd.DataFrame, cost_rate: float) -> pd.DataFrame:
    rows = []
    for strategy, group in backtest_returns.groupby("strategy", sort=True):
        for return_type, column, tx_rate in [
            ("gross", "gross_return", 0.0),
            ("net", "net_return", cost_rate),
        ]:
            rows.append(
                {
                    "strategy": strategy,
                    "strategy_group": MODEL_GROUPS.get(strategy, BENCHMARKS.get(strategy, "other")),
                    "return_type": return_type,
                    "transaction_cost_rate": tx_rate,
                    "strategy_note": STRATEGY_NOTES.get(strategy, ""),
                    **evaluate_returns(group[column], group["turnover"]),
                }
            )
    return pd.DataFrame(rows).sort_values(["return_type", "strategy"]).reset_index(drop=True)


def build_equity_curves(backtest_returns: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for strategy, group in backtest_returns.groupby("strategy", sort=True):
        ordered = group.sort_values("date")
        gross_wealth = (1.0 + ordered["gross_return"].fillna(0.0)).cumprod()
        net_wealth = (1.0 + ordered["net_return"].fillna(0.0)).cumprod()
        gross_drawdown = drawdown_series_from_wealth(gross_wealth)
        net_drawdown = drawdown_series_from_wealth(net_wealth)
        for row, gross, net, gross_dd, net_dd in zip(
            ordered.itertuples(index=False),
            gross_wealth,
            net_wealth,
            gross_drawdown,
            net_drawdown,
            strict=False,
        ):
            rows.append(
                {
                    "date": row.date,
                    "strategy": row.strategy,
                    "gross_wealth": float(gross),
                    "net_wealth": float(net),
                    "gross_drawdown": float(gross_dd),
                    "net_drawdown": float(net_dd),
                    "gross_return": float(row.gross_return),
                    "net_return": float(row.net_return),
                    "turnover": float(row.turnover),
                    "transaction_cost": float(row.transaction_cost),
                }
            )
    return pd.DataFrame(rows).sort_values(["strategy", "date"]).reset_index(drop=True)


def build_excess_returns(backtest_returns: pd.DataFrame, benchmark: str) -> pd.DataFrame:
    pivot = backtest_returns.pivot(index="date", columns="strategy", values="net_return").sort_index()
    if benchmark not in pivot.columns:
        raise ValueError(f"Benchmark {benchmark} is not available in return table.")

    rows = []
    benchmark_returns = pivot[benchmark]
    for strategy in pivot.columns:
        if strategy == benchmark:
            continue
        excess = (pivot[strategy] - benchmark_returns).dropna()
        tracking_error = (
            float(excess.std(ddof=1) * np.sqrt(MONTHS_PER_YEAR)) if len(excess) > 1 else 0.0
        )
        annual_excess = float(excess.mean() * MONTHS_PER_YEAR) if len(excess) else 0.0
        rows.append(
            {
                "strategy": strategy,
                "benchmark": benchmark,
                "months": int(len(excess)),
                "annual_excess_return": annual_excess,
                "tracking_error": tracking_error,
                "information_ratio": annual_excess / tracking_error if tracking_error > 0 else 0.0,
                "excess_win_rate": float((excess > 0).mean()) if len(excess) else 0.0,
                "cumulative_excess_return": float((1.0 + excess).prod() - 1.0) if len(excess) else 0.0,
            }
        )
    return pd.DataFrame(rows).sort_values("annual_excess_return", ascending=False)


def build_cost_sensitivity(backtest_returns: pd.DataFrame, cost_rates: list[float]) -> pd.DataFrame:
    rows = []
    for strategy, group in backtest_returns.groupby("strategy", sort=True):
        for cost_rate in cost_rates:
            simulated = group["gross_return"] - cost_rate * group["turnover"]
            rows.append(
                {
                    "strategy": strategy,
                    "cost_rate": cost_rate,
                    **evaluate_returns(simulated, group["turnover"]),
                }
            )
    return pd.DataFrame(rows).sort_values(["cost_rate", "strategy"]).reset_index(drop=True)


def normalize_score(series: pd.Series, higher_is_better: bool = True) -> pd.Series:
    values = series.astype(float)
    if not higher_is_better:
        values = -values
    spread = values.max() - values.min()
    if spread <= 1e-12:
        return pd.Series(0.5, index=series.index)
    return (values - values.min()) / spread


def rank_models(metrics: pd.DataFrame) -> pd.DataFrame:
    net = metrics[
        (metrics["return_type"] == "net") & (metrics["strategy_group"] != "benchmark")
    ].copy()
    net["quality_score"] = (
        0.25 * normalize_score(net["annual_return"])
        + 0.20 * normalize_score(net["sharpe"])
        + 0.20 * normalize_score(net["max_drawdown"], higher_is_better=True)
        + 0.15 * normalize_score(net["win_rate"])
        + 0.10 * normalize_score(net["average_turnover"], higher_is_better=False)
        + 0.10 * normalize_score(net["calmar"])
    )
    net["rank"] = net["quality_score"].rank(ascending=False, method="first").astype(int)
    columns = [
        "rank",
        "strategy",
        "strategy_group",
        "quality_score",
        "total_return",
        "annual_return",
        "annual_volatility",
        "sharpe",
        "calmar",
        "max_drawdown",
        "win_rate",
        "average_turnover",
    ]
    return net.sort_values("rank")[columns].reset_index(drop=True)


def strategy_assessment(row: pd.Series) -> tuple[str, str]:
    strategy = row["strategy"]
    strength_parts = []
    weakness_parts = []

    if row["annual_return"] >= 0.20:
        strength_parts.append("年化收益领先")
    elif row["annual_return"] >= 0.12:
        strength_parts.append("年化收益中等偏稳")
    else:
        weakness_parts.append("净收益不足")

    if row["sharpe"] >= 2.0:
        strength_parts.append("风险调整收益强")
    elif row["sharpe"] < 1.0:
        weakness_parts.append("Sharpe 偏低")

    if row["max_drawdown"] > -0.05:
        strength_parts.append("回撤控制好")
    elif row["max_drawdown"] < -0.10:
        weakness_parts.append("回撤压力大")

    if row["average_turnover"] > 1.0:
        weakness_parts.append("换手高且交易成本敏感")
    elif row["average_turnover"] < 0.7:
        strength_parts.append("换手相对可控")

    if strategy == "spo_plus_fee":
        weakness_parts.append("当前输出与基础 SPO+ 几乎重合，费用项没有形成有效约束")
    if strategy == "spo_plus_turnover_l2":
        strength_parts.append("正则化显著改善基础 SPO+ 的净值表现")
    if strategy.startswith("ai_"):
        strength_parts.append("风险约束让波动和回撤更平滑")

    strength = "；".join(dict.fromkeys(strength_parts)) or "没有明显优势"
    weakness = "；".join(dict.fromkeys(weakness_parts)) or "主要风险来自样本期较短"
    return strength, weakness


def build_model_assessment(metrics: pd.DataFrame, ranking: pd.DataFrame) -> pd.DataFrame:
    net_models = metrics[
        (metrics["return_type"] == "net") & (metrics["strategy_group"] != "benchmark")
    ].copy()
    rank_lookup = ranking.set_index("strategy")["rank"].to_dict()
    rows = []
    for _, row in net_models.sort_values("annual_return", ascending=False).iterrows():
        strength, weakness = strategy_assessment(row)
        rows.append(
            {
                "rank": int(rank_lookup[row["strategy"]]),
                "strategy": row["strategy"],
                "strategy_group": row["strategy_group"],
                "strengths": strength,
                "weaknesses": weakness,
                "recommended_use": recommended_use(row),
            }
        )
    return pd.DataFrame(rows).sort_values("rank").reset_index(drop=True)


def recommended_use(row: pd.Series) -> str:
    strategy = row["strategy"]
    if strategy == "ai_low_risk":
        return "适合作为低波动核心组合或防守档位。"
    if strategy == "ai_medium_risk":
        return "适合作为当前样本下的主组合候选，收益和风险比较均衡。"
    if strategy == "ai_high_risk":
        return "适合愿意承受更高波动、追求更高收益弹性的配置。"
    if strategy == "spo_plus_turnover_l2":
        return "适合作为 SPO 类策略的生产化起点，但需要继续降低换手。"
    if strategy == "pto_markowitz":
        return "适合作为传统 PtO/Markowitz 对照模型，不宜忽略成本。"
    if strategy in {"spo_plus", "spo_plus_fee"}:
        return "更适合保留为消融实验基线，而非直接实盘化。"
    return "适合作为比较样本。"


def format_pct(value: float) -> str:
    return f"{value * 100:.2f}%"


def format_float(value: float) -> str:
    return f"{value:.2f}"


def markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    if frame.empty:
        return "_No rows._"
    headers = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join(["---"] * len(columns)) + " |"
    lines = [headers, sep]
    for _, row in frame[columns].iterrows():
        values = []
        for col in columns:
            value = row[col]
            if isinstance(value, (bool, np.bool_)):
                values.append("通过" if bool(value) else "未通过")
            elif isinstance(value, float):
                if any(token in col for token in ["return", "volatility", "drawdown", "rate", "turnover"]):
                    values.append(format_pct(value))
                elif "score" in col or "sharpe" in col or "ratio" in col or "calmar" in col:
                    values.append(format_float(value))
                else:
                    values.append(str(round(value, 4)))
            else:
                values.append(str(value))
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def build_report(
    metrics: pd.DataFrame,
    ranking: pd.DataFrame,
    excess: pd.DataFrame,
    model_assessment: pd.DataFrame,
    prediction_metrics: pd.DataFrame,
    lookahead_audit: dict[str, Any],
    plot_paths: dict[str, str],
    validation_summary: dict[str, Any],
    args: argparse.Namespace,
) -> str:
    net = metrics[metrics["return_type"] == "net"].sort_values("annual_return", ascending=False)
    gross = metrics[metrics["return_type"] == "gross"].sort_values("annual_return", ascending=False)
    best_model = ranking.iloc[0]
    best_risk = metrics[metrics["return_type"] == "net"].sort_values("sharpe", ascending=False).iloc[0]

    spo_meta = validation_summary.get("spo_metadata", {})
    data_meta = spo_meta.get("data", {})
    period = (
        f"{data_meta.get('test_start', 'unknown')} to {data_meta.get('test_end', 'unknown')}"
        if data_meta
        else "derived from existing backtest tables"
    )
    months = int(net["months"].max()) if not net.empty else 0

    lines = [
        "# 既有模型回测评估报告",
        "",
        "## 回测范围",
        "",
        (
            "本报告只评估仓库已有模型和策略输出，不重新训练 SPO/PtO 主模型。"
            f"测试区间为 {period}，共 {months} 个按月调仓样本。"
            f"主表同时保留扣成本前后的指标，扣成本后结果按单边交易成本 {args.cost_rate:.4f} 重新计算。"
        ),
        "",
        "## 主要结论",
        "",
        (
            f"综合评分最优的既有模型是 `{best_model['strategy']}`：扣成本后年化收益 "
            f"{format_pct(best_model['annual_return'])}，Sharpe {format_float(best_model['sharpe'])}，"
            f"最大回撤 {format_pct(best_model['max_drawdown'])}，Calmar "
            f"{format_float(best_model['calmar'])}。风险调整收益最高的是 `{best_risk['strategy']}`，"
            f"Sharpe 为 {format_float(best_risk['sharpe'])}。"
        ),
        "",
        "## 未来函数控制",
        "",
        (
            f"审计结果：{'通过' if lookahead_audit.get('all_checks_passed') else '存在待复核项'}。"
            "本回测遵循：t 月末只使用 t 月末及以前数据，预测未来 21 个交易日收益，"
            "组合收益使用下一期真实收益；StandardScaler 只在训练集 fit，"
            "验证集和测试集只 transform。"
        ),
        "",
        markdown_table(pd.DataFrame(lookahead_audit.get("checks", [])), ["rule", "status", "evidence"]),
        "",
        "## 交易成本口径",
        "",
        (
            "扣成本后收益按以下公式逐月复算："
            "`turnover_t = sum(abs(weight_t - weight_{t-1}))`，"
            "`cost_t = turnover_t * cost_rate`，"
            "`net_return_t = gross_return_t - cost_t`。"
            "主结果使用课程建议范围内的 0.10% 单边成本；敏感性表额外给出 "
            "0%、0.05%、0.10%、0.25%、0.50%、1.00%。"
        ),
        "",
        "## 扣成本后模型排名",
        "",
        markdown_table(
            ranking,
            [
                "rank",
                "strategy",
                "strategy_group",
                "quality_score",
                "annual_return",
                "annual_volatility",
                "sharpe",
                "calmar",
                "max_drawdown",
                "win_rate",
                "average_turnover",
            ],
        ),
        "",
        "## 策略绩效对比表（扣成本后）",
        "",
        markdown_table(
            net,
            [
                "strategy",
                "strategy_group",
                "total_return",
                "annual_return",
                "annual_volatility",
                "sharpe",
                "calmar",
                "max_drawdown",
                "win_rate",
                "average_turnover",
            ],
        ),
        "",
        "## 策略绩效对比表（扣成本前）",
        "",
        markdown_table(
            gross,
            [
                "strategy",
                "strategy_group",
                "total_return",
                "annual_return",
                "annual_volatility",
                "sharpe",
                "calmar",
                "max_drawdown",
                "win_rate",
                "average_turnover",
            ],
        ),
        "",
        f"## 相对 `{args.benchmark}` 的超额表现",
        "",
        markdown_table(
            excess,
            [
                "strategy",
                "annual_excess_return",
                "tracking_error",
                "information_ratio",
                "excess_win_rate",
                "cumulative_excess_return",
            ],
        ),
        "",
        "## 既有模型优劣评价",
        "",
        markdown_table(
            model_assessment,
            [
                "rank",
                "strategy",
                "strategy_group",
                "strengths",
                "weaknesses",
                "recommended_use",
            ],
        ),
        "",
        "## 预测层诊断",
        "",
        markdown_table(
            prediction_metrics,
            ["model_name", "split", "rmse", "mae", "r2", "rank_ic"],
        ),
        "",
        "## 图表输出",
        "",
        "- ETF 价格或净值走势：`plots/etf_price_index.png`",
        "- 各策略累计收益曲线：`plots/strategy_cumulative_returns.png`",
        "- 各策略最大回撤曲线：`plots/strategy_drawdowns.png`",
        "- AI 组合月度权重热力图：`plots/ai_monthly_weight_heatmap.png`",
        "- 随机森林特征重要性图：`plots/random_forest_feature_importance.png`",
        "- 策略绩效对比表：`plots/strategy_performance_table.png`",
        "",
        "## 结果解释",
        "",
        "- AI 风险画像组合在本样本中领先，因为它把 SPO/PtO 信号与波动率、单资产上限等组合约束结合，净值路径比原始 SPO 更平滑。",
        "- 原始 `spo_plus` 能体现决策导向训练思路，但仓位集中、换手偏高；加入 turnover/L2 的 `spo_plus_turnover_l2` 明显改善净收益和回撤。",
        "- `pto_markowitz` 扣成本前表现有竞争力，但换手和回撤压力较大，扣成本后优势明显下降。",
        "- 等权组合仍是很强的基准。可交付模型不仅要扣成本前领先，也要在扣成本后超过等权基准。",
        "",
        "## 生成文件",
        "",
        "- `strategy_backtest_metrics.csv`: recomputed gross/net metrics for every strategy.",
        "- `strategy_equity_curves.csv`: monthly gross and net wealth curves.",
        "- `strategy_drawdown_curves.csv`: monthly gross and net drawdown curves.",
        "- `strategy_excess_returns.csv`: net excess diagnostics versus the selected benchmark.",
        "- `transaction_cost_sensitivity.csv`: metrics under several cost assumptions.",
        "- `model_quality_ranking.csv`: standalone scorecard for non-benchmark models.",
        "- `model_assessment.csv`: Chinese strengths, weaknesses, and usage recommendations.",
        "- `lookahead_audit.json`: machine-readable look-ahead-bias audit.",
        "- `random_forest_feature_importance.csv`: RF feature importance fit on train split only.",
        "- `backtest_summary.json`: machine-readable summary and validation snapshot.",
        "",
        "本项目仅用于课程案例研究，不构成任何投资建议。",
    ]
    return "\n".join(lines) + "\n"


def finite_check(frame: pd.DataFrame, columns: list[str]) -> bool:
    if frame.empty:
        return False
    return bool(np.isfinite(frame[columns].to_numpy(dtype=float)).all())


def write_outputs(
    output_dir: Path,
    backtest_returns: pd.DataFrame,
    metrics: pd.DataFrame,
    curves: pd.DataFrame,
    excess: pd.DataFrame,
    cost_sensitivity: pd.DataFrame,
    ranking: pd.DataFrame,
    model_assessment: pd.DataFrame,
    feature_importance: pd.DataFrame,
    lookahead_audit: dict[str, Any],
    plot_paths: dict[str, str],
    report: str,
    prediction_metrics: pd.DataFrame,
    validation_summary: dict[str, Any],
    args: argparse.Namespace,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    backtest_returns.to_csv(output_dir / "combined_model_backtest_returns.csv", index=False)
    metrics.to_csv(output_dir / "strategy_backtest_metrics.csv", index=False)
    curves.to_csv(output_dir / "strategy_equity_curves.csv", index=False)
    curves[["date", "strategy", "gross_drawdown", "net_drawdown"]].to_csv(
        output_dir / "strategy_drawdown_curves.csv",
        index=False,
    )
    excess.to_csv(output_dir / "strategy_excess_returns.csv", index=False)
    cost_sensitivity.to_csv(output_dir / "transaction_cost_sensitivity.csv", index=False)
    ranking.to_csv(output_dir / "model_quality_ranking.csv", index=False)
    model_assessment.to_csv(output_dir / "model_assessment.csv", index=False)
    feature_importance.to_csv(output_dir / "random_forest_feature_importance.csv", index=False)
    (output_dir / "lookahead_audit.json").write_text(
        json.dumps(lookahead_audit, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (output_dir / "existing_model_backtest_report.md").write_text(report, encoding="utf-8")

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "input_dir": args.input_dir,
        "output_dir": str(output_dir),
        "benchmark": args.benchmark,
        "cost_rate": args.cost_rate,
        "transaction_cost_formula": "net_return_t = gross_return_t - sum(abs(weight_t - weight_t-1)) * cost_rate",
        "strategies": sorted(backtest_returns["strategy"].unique().tolist()),
        "best_model_by_quality_score": ranking.iloc[0].to_dict() if not ranking.empty else None,
        "best_strategy_by_net_sharpe": (
            metrics[metrics["return_type"] == "net"]
            .sort_values("sharpe", ascending=False)
            .iloc[0]
            .to_dict()
        ),
        "validation": {
            "metrics_finite_ok": finite_check(
                metrics,
                [
                    "total_return",
                    "annual_return",
                    "annual_volatility",
                    "sharpe",
                    "sortino",
                    "max_drawdown",
                    "calmar",
                    "win_rate",
                    "average_turnover",
                ],
            ),
            "curve_rows": int(len(curves)),
            "return_rows": int(len(backtest_returns)),
            "prediction_metric_rows": int(len(prediction_metrics)),
            "lookahead_audit_passed": bool(lookahead_audit.get("all_checks_passed", False)),
        },
        "plots": plot_paths,
        "source_validation_summary": validation_summary,
    }
    (output_dir / "backtest_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def main() -> None:
    args = parse_args()
    root = project_root()
    input_dir = root / args.input_dir
    output_dir = root / args.output_dir

    raw_backtest_returns = read_existing_returns(input_dir)
    backtest_returns = apply_transaction_cost(raw_backtest_returns, args.cost_rate)
    prediction_metrics = read_prediction_metrics(input_dir)
    validation_summary = read_validation_summary(input_dir)
    feature_metadata = read_feature_metadata(root)
    price_index = read_price_index(root)
    weights = read_strategy_weights(input_dir)

    metrics = calculate_metrics(backtest_returns, args.cost_rate)
    curves = build_equity_curves(backtest_returns)
    excess = build_excess_returns(backtest_returns, args.benchmark)
    cost_sensitivity = build_cost_sensitivity(
        backtest_returns,
        cost_rates=sorted(set([0.0, 0.0005, 0.001, 0.0025, 0.005, 0.01, args.cost_rate])),
    )
    ranking = rank_models(metrics)
    model_assessment = build_model_assessment(metrics, ranking)
    output_dir.mkdir(parents=True, exist_ok=True)
    feature_importance = build_random_forest_feature_importance(root, feature_metadata, output_dir)
    lookahead_audit = build_lookahead_audit(
        root,
        input_dir,
        backtest_returns,
        feature_metadata,
        validation_summary,
    )
    plot_paths = save_all_plots(
        price_index,
        curves,
        weights,
        metrics,
        feature_importance,
        output_dir,
    )
    report = build_report(
        metrics,
        ranking,
        excess,
        model_assessment,
        prediction_metrics,
        lookahead_audit,
        plot_paths,
        validation_summary,
        args,
    )

    write_outputs(
        output_dir,
        backtest_returns,
        metrics,
        curves,
        excess,
        cost_sensitivity,
        ranking,
        model_assessment,
        feature_importance,
        lookahead_audit,
        plot_paths,
        report,
        prediction_metrics,
        validation_summary,
        args,
    )

    print(f"Backtest evaluation written to {output_dir}")
    print(f"Best model: {ranking.iloc[0]['strategy']} (score={ranking.iloc[0]['quality_score']:.3f})")


if __name__ == "__main__":
    main()
